In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('./../data/train.csv', dtype={
                    'cust_id': 'int64',
                    'gender': 'category',
                    'age': 'int8',
                    'driving_license': 'category',
                    'region_code': 'category',
                    'previously_insured': 'category',
                    'vehicle_age': 'category',
                    'vehicle_damage': 'category',
                    'annual_premium': 'float16',
                    'policy_sales_channel': 'category',
                    'days_since_insured': 'int8',
                    'response': 'bool',
                 })

In [3]:
train_data.head()

,cust_id,gender,age,driving_license,region_code,previously_insured,vehicle_age,vehicle_damage,annual_premium,policy_sales_channel,days_since_insured,response
0,167647,Male,22,1,7.0,1,< 1 Year,No,52.59375,152.0,16,False
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,866.50000,26.0,-121,False
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,717.00000,124.0,-3,False
3,87447,Female,22,1,33.0,0,< 1 Year,No,553.00000,152.0,69,False
4,501933,Male,28,1,46.0,1,< 1 Year,No,580.50000,152.0,-45,False

In [4]:
from pycaret.classification import *

### Experiment: Using the companyId as the categorical feature

In [5]:
reg = setup(data=train_data, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel', 'region_code'], experiment_name='churn1')

In [6]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [ ]:
# best = compare_models(include=['nb', 'dt', 'svm', 'rbfsvm', 'gpc', 'mlp', 'rf', 'qda', 'ada', 'gbc', 'et', 'xgboost', 'lightgbm', 'catboost', 'dummy'], fold=3)
best = compare_models(include=['nb', 'dt', 'svm', 'gpc', 'mlp', 'rf', 'qda', 'ada', 'gbc', 'et', 'xgboost', 'lightgbm', 'catboost', 'dummy'], fold=3)

IntProgress(value=0, description='Processing: ', max=79)

Initiated  . . . . . . . . . . . . . . . . . .             01:32:09
Status     . . . . . . . . . . . . . . . . . .      Fitting 3 Folds
Estimator  . . . . . . . . . . . . . . . . . .  SVM - Radial Kernel

/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute standard_coef_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute standard_intercept_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute average_coef_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute average_intercept_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute standard_coef_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute standard_intercept_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute average_coef_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)
/Users/I329382/opt/anaconda3/envs/churn/lib/python3.8/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute average_intercept_ was deprecated in version 0.23 and will be removed in 0.25.
  warnings.warn(msg, category=FutureWarning)

In [9]:
best

[LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=4096, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0),
 GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                           init=None, learning_rate=0.1, loss='ls', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=4096, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0, warm_start=False),
 Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
       normalize=False, random_state=4096, solver='auto', tol=0.001)]

In [ ]:
## comparing with the other boosting algorithms

In [15]:
best = compare_models(n_select=3, fold=5, exclude = ['rf', 'et'])

## Experiment: Comparing models by making companyId as a high cardinality feature

In [10]:
reg1 = setup(data=train_data, target='salary', ignore_features=['jobId'], high_cardinality_features = ['companyId'], log_experiment=True, experiment_name='salary2')

In [18]:
best1 = compare_models(n_select=3, fold=5, exclude = ['rf', 'et', 'knn'])

In [19]:
best1

[<catboost.core.CatBoostRegressor at 0x1b29550c4f0>,
 LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=5179, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0),
 XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=-1, num_parallel_tree=1, objective='reg:squarederror',
              predictor='auto', random_state=5179, reg_alpha=0, ...)]

In [21]:
evaluate_model(best1[0])

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [22]:
save_model(best1[0], 'my_best_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True,
                                       features_todrop=['jobId'], id_columns=[],
                                       ml_usecase='regression',
                                       numerical_features=[], target='salary',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_st...
                 ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                 ('cluster_all', 'passthrough'),
                 ('dummy', Dummify(target='salary')),
                 ('fix_perfect', Remove_100(target='salary')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  <catboost.core.CatBoostRegressor object at 0x000001B29550C4F0>]],
          verbose=False),
 'my_best_pipeline.pkl')

## Experiment: Using Polynomial Features

In [6]:
reg3 = setup(data=train_data, target='salary', ignore_features=['jobId'], high_cardinality_features = ['companyId'],
            log_experiment=True, polynomial_features = True, experiment_name='salary3')

In [7]:
best3 = compare_models(n_select=3, fold=5, exclude = ['rf', 'et', 'knn'])