In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('./../data/train.csv', dtype={
                    'cust_id': 'int64',
                    'gender': 'category',
                    'age': 'int8',
                    'driving_license': 'category',
                    'region_code': 'category',
                    'previously_insured': 'category',
                    'vehicle_age': 'category',
                    'vehicle_damage': 'category',
                    'annual_premium': 'float16',
                    'policy_sales_channel': 'category',
                    'days_since_insured': 'int8',
                    'response': 'bool',
                 })

In [3]:
train_data.head()

,cust_id,gender,age,driving_license,region_code,previously_insured,vehicle_age,vehicle_damage,annual_premium,policy_sales_channel,days_since_insured,response
0,167647,Male,22,1,7.0,1,< 1 Year,No,52.59375,152.0,16,False
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,866.50000,26.0,-121,False
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,717.00000,124.0,-3,False
3,87447,Female,22,1,33.0,0,< 1 Year,No,553.00000,152.0,69,False
4,501933,Male,28,1,46.0,1,< 1 Year,No,580.50000,152.0,-45,False

In [4]:
from pycaret.classification import *

### Experiment: Using the companyId as the categorical feature

In [5]:
reg = setup(data=train_data, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel', 'region_code'], experiment_name='churn1')

In [6]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [7]:
# best = compare_models(include=['nb', 'dt', 'svm', 'rbfsvm', 'gpc', 'mlp', 'rf', 'qda', 'ada', 'gbc', 'et', 'xgboost', 'lightgbm', 'catboost', 'dummy'], fold=3)
best = compare_models(include=['nb', 'dt', 'svm', 'gpc', 'mlp', 'rf', 'qda', 'ada', 'gbc', 'et', 'xgboost', 'lightgbm', 'catboost', 'dummy'], fold=3)

## Experiment: Using only region 28

In [8]:
train_data['region_code'].value_counts()

28.0    107199
8.0      33941
46.0     20203
41.0     19090
15.0     13071
30.0     12742
29.0     11650
50.0     10176
11.0      9392
3.0       9276
36.0      8619
33.0      8008
35.0      7254
47.0      7251
6.0       6565
45.0      5555
18.0      5392
37.0      5016
14.0      4884
10.0      4509
39.0      4476
21.0      4431
48.0      4333
13.0      4030
2.0       3723
7.0       3284
12.0      3162
9.0       2936
32.0      2714
43.0      2580
27.0      2544
17.0      2517
25.0      2471
26.0      2438
24.0      2385
38.0      2014
23.0      2005
16.0      2001
0.0       1839
4.0       1825
31.0      1752
20.0      1710
49.0      1709
34.0      1543
19.0      1473
22.0      1261
40.0      1242
5.0       1213
1.0        940
44.0       784
42.0       567
52.0       263
51.0       196
Name: region_code, dtype: int64

In [9]:
train_data_28 = train_data.loc[train_data['region_code'] == '28.0']

In [10]:
train_data_28.shape

(107199, 12)

In [11]:
train_data_28 = train_data_28.loc[:, train_data_28.columns!='region_code']

In [12]:
train_data_28.head()

,cust_id,gender,age,driving_license,previously_insured,vehicle_age,vehicle_damage,annual_premium,policy_sales_channel,days_since_insured,response
1,17163,Male,42,1,0,1-2 Year,Yes,866.50000,26.0,-121,False
7,331781,Male,38,1,1,1-2 Year,No,52.59375,26.0,51,False
8,290704,Female,45,1,0,1-2 Year,Yes,1118.00000,124.0,6,False
9,344792,Male,42,1,0,1-2 Year,Yes,556.00000,122.0,-39,True
12,441774,Male,33,1,0,< 1 Year,Yes,508.75000,122.0,-91,True

In [13]:
clf = setup(data=train_data_28, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [14]:
best = compare_models(fold=3)

# Experiment: Using region not 28

In [16]:
train_data_not_28 = train_data.loc[train_data['region_code'] != '28.0']

In [17]:
train_data_not_28.shape

(274955, 12)

In [18]:
train_data_not_28 = train_data_not_28.loc[:, train_data_not_28.columns!='region_code']

In [19]:
clf = setup(data=train_data_not_28, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [20]:
best = compare_models(fold=3)

# Experiment: Using region 8

In [21]:
train_data_8 = train_data.loc[train_data['region_code'] == '8.0']

In [22]:
train_data_8 = train_data_8.loc[:, train_data_8.columns!='region_code']

In [23]:
clf = setup(data=train_data_8, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [24]:
best = compare_models(fold=3)

# Experiment using region 46

In [25]:
train_data_46 = train_data.loc[train_data['region_code'] == '46.0']

In [26]:
train_data_46 = train_data_46.loc[:, train_data_46.columns!='region_code']

In [27]:
clf = setup(data=train_data_46, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [28]:
best = compare_models(fold=3)

# Experiment using the region code 41

In [29]:
train_data_41 = train_data.loc[train_data['region_code'] == '41.0']

In [30]:
train_data_41 = train_data_41.loc[:, train_data_41.columns!='region_code']

In [31]:
clf = setup(data=train_data_41, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [32]:
best = compare_models(fold=3)

In [34]:
train_data_generic = train_data.loc[~train_data['region_code'].isin(['41.0', '28.0', '8.0', '46.0'])]

In [35]:
train_data_generic.shape

(201721, 12)

In [36]:
train_data_generic['region_code'].unique()

['7.0', '33.0', '25.0', '39.0', '13.0', ..., '17.0', '51.0', '0.0', '23.0', '44.0']
Length: 49
Categories (53, object): ['0.0', '1.0', '10.0', '11.0', ..., '6.0', '7.0', '8.0', '9.0']

In [37]:
clf = setup(data=train_data_generic, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel'], experiment_name='churn1')

In [38]:
best = compare_models(fold=3)

In [39]:
train_data_with_small_regions = train_data.loc[~train_data['region_code'].isin(['41.0', '28.0', '8.0', '46.0'])]

In [41]:
clf = setup(data=train_data_with_small_regions, target='response', ignore_features=['cust_id'],
            categorical_features=['gender', 'driving_license', 'previously_insured', 'vehicle_age', 'vehicle_damage'],
            high_cardinality_features=['policy_sales_channel', 'region_code'], experiment_name='churn1')

In [42]:
best = compare_models(fold=3)